---
title: "Homework II"
author: "Wen Yuan Yen"
date: "10/22/2018"
output:
  pdf_document: default
  html_document: default
---

# 1.
##1.1
$$1 - p_i$$

##1.2
$$(1 - p_i)^n$$

##1.3
$$1-(1 - p_i)^n$$

# 2.

```{r}
load("/Users/wenyuanyen/Desktop/schooldistrict.RData")

# define auxiliary variable, X
X <- schooldistrict$TOTTCH01 

# By the definition of pps, those units with X == NA or == 0 will never be sampled
# So, we can delete them before doing sampling procedure

sorted <- schooldistrict[order(X, na.last= NA), ] # sort and delete X == NA
sorted <- sorted[which(sorted$TOTTCH01 != 0), ]   # delete X == 0
p <- sorted$TOTTCH01 / sum(sorted$TOTTCH01)       # per-draw selection probabilities
N <- nrow(sorted)        # Number of units for which p > 0, denoted by N

# iterations to take population units for which X >= I
large <- N
n <- 100

while(TRUE){
  I <- sum(sorted$TOTTCH01[1:large]) / n
  last <- tail(sorted$TOTTCH01[1:large], 1)
  if(last >= I){
    large <- large - 1
    n <- n - 1
  } else {
    break }
}

index_L <- c((large+1):N)
```

```{r echo=FALSE}
paste("After the iterations, we are left",n, 'samples to be sampled', sep = " ")
paste("Skip interval I is ",round(I,3) , sep = " ")
paste("Maximum of X in the remaining units is", max(sorted$TOTTCH01[1:large]) , sep = ' ')
```

```{r}
## Sample 97 units from sorted$TOTTCH01[1:large]

# choose R from uniform(0, I]
set.seed(331)
R <- runif(1,min = 0, max = I)

# compute selection number and partial sum of X
selection <- R + I * c( 0:(n-1) )
M <- cumsum( sorted$TOTTCH01[1:large] )

# min of which function is the first sample whose M >= selection number
index <- c()
for(i in 1:n){ 
  index[i] <- min(   which( M >= selection[i] )   ) 
  }

index <- c(index, index_L)
sample <- sorted[index, ] # 100 samples
```

# 3. 

Estimated total number of students is 49,627,986. While true population total is 47,767,834.
```{r}
y <- sample$PK1201
z <- y / p[index]

mean(z, na.rm=TRUE) # estimated population total
sum(schooldistrict$PK1201, na.rm = TRUE) # true population total
```


# 4.

Estimated variance of the estimator is  773,275,863,203
```{r}
1 / 100 * var(z, na.rm = TRUE)
```

# 5.

Sample size should be greater than or equal to 367.


$$1.96 \sqrt{Var(\hat P)} < 0.05$$
$$ \Rightarrow 1.96^2 \Big[ \underbrace{(1-f)}_{\approx1}\frac{1}{n}\underbrace{\frac{N}{N-1}}_{\approx1} p'(1-p')\Big] < 0.05^2$$

$$ \Rightarrow 1.96^2 \frac{p'(1-p')}{0.05^2}= 245.862< n $$
$$\Rightarrow  0.67n' > 245.862 $$
$$ n' = 367 $$


